# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Sponsor.delete_all
Sponsor.create([{ name: 'Bendyworks',
               twitter: '@bendycode',
               website: 'bendyworks.com',
               description: """Pop-up YOLO cred gluten-free dolore tempor, pour-over assumenda vice synth blog mlkshk salvia mcsweeney's bushwick. Mixtape sunt tattooed, carles nihil flannel odd future literally tumblr pickled sartorial. Blue bottle assumenda farm-to-table, beard banjo brooklyn ut Austin lo-fi 3 wolf moon veniam commodo sed qui. Direct trade actually tumblr biodiesel. Irure flexitarian kogi beard banksy. Exercitation plaid narwhal, mumblecore excepteur aesthetic synth gluten-free jean shorts. Tempor scenester artisan, blog fanny pack est umami lo-fi.
                    Literally mumblecore pitchfork street art sartorial, blog magna whatever viral irony aesthetic chillwave kogi fashion axe fixie. Enim cred laborum occupy chillwave assumenda tempor godard exercitation, et swag. Tofu reprehenderit sartorial, disrupt lomo pour-over lo-fi organic sunt. Gluten-free artisan velit ethical marfa. Labore neutra veniam thundercats butcher. Culpa fashion axe synth carles, helvetica street art deep v consectetur church-key forage fixie 3 wolf moon hella mollit nesciunt. Synth ullamco cray fashion axe, deep v brunch in lomo farm-to-table stumptown accusamus kale chips deserunt ethnic you probably haven't heard of them.
                    Carles ethical chambray, PBR odd future keytar quis. Placeat hashtag keffiyeh fingerstache craft beer pour-over. Gentrify brooklyn disrupt polaroid portland, minim sartorial fanny pack forage four loko messenger bag. Proident williamsburg tattooed portland intelligentsia qui typewriter, delectus veniam polaroid letterpress shoreditch. Etsy elit Austin synth gentrify retro. Single-origin coffee magna id, church-key narwhal bushwick umami odio whatever assumenda laborum 3 wolf moon pinterest iphone. Blog helvetica whatever, flannel vegan tonx consectetur kogi photo booth sartorial sapiente exercitation.
                    Accusamus qui quinoa stumptown, leggings shoreditch messenger bag twee plaid sapiente commodo post-ironic DIY helvetica odio. Skateboard artisan nisi aesthetic. +1 meggings fanny pack, etsy organic post-ironic accusamus fashion axe veniam helvetica assumenda street art deserunt fixie. Quinoa gentrify fingerstache 90's, helvetica fugiat blue bottle. Deep v jean shorts do cred mustache YOLO. Pinterest sustainable lomo, squid fanny pack duis culpa DIY incididunt tattooed retro. Proident adipisicing sunt nulla, cupidatat culpa chambray blue bottle."""
                },
                  { name: 'GitHub',
                    twitter: '@github',
                    website: 'github.com',
                    description: """Messenger bag pork belly wolf odio, cray organic intelligentsia incididunt small batch deserunt nisi id velit umami. Brooklyn banksy aesthetic, ut enim VHS echo park master cleanse assumenda. Master cleanse wayfarers banjo, tofu meh voluptate odio salvia irony echo park fap. Proident cardigan ugh, 8-bit wes anderson fugiat ea. Irony PBR artisan carles brooklyn, est gastropub nulla high life pickled assumenda banksy umami occupy DIY. Photo booth qui commodo jean shorts, gluten-free odd future excepteur godard. Dreamcatcher try-hard Austin, truffaut godard mlkshk whatever neutra laboris fugiat williamsburg.
                        Ugh fap tonx occaecat, bicycle rights mcsweeney's dreamcatcher eu banjo carles literally. Laborum officia post-ironic, yr swag aesthetic flexitarian kogi scenester portland irure biodiesel minim 3 wolf moon. Ugh wolf semiotics laboris, you probably haven't heard of them squid intelligentsia irony. Pour-over elit mustache brunch thundercats, cupidatat sartorial seitan photo booth nulla american apparel. Lomo salvia semiotics banjo, consectetur typewriter lo-fi culpa terry richardson est pop-up ethnic vice jean shorts locavore. Officia lo-fi flexitarian, jean shorts mixtape viral beard esse disrupt. Raw denim tofu ut, salvia deep v dreamcatcher vice tattooed ethnic marfa echo park.
                        Ex eiusmod exercitation veniam. Sartorial meh raw denim aliqua, magna ea salvia fap. Cray labore mumblecore, butcher blog locavore post-ironic tempor ex shoreditch flexitarian non readymade. Intelligentsia odd future bicycle rights nulla wayfarers fugiat butcher enim, cillum sint food truck accusamus fashion axe. Officia do carles aliqua accusamus keytar aliquip iphone, church-key thundercats high life terry richardson sriracha organic. Banh mi cardigan meh, exercitation selvage american apparel duis kogi dolor 3 wolf moon wolf. Swag tofu commodo, minim thundercats eiusmod cillum sint umami try-hard gentrify freegan velit accusamus.
                        Mustache cray hoodie next level fap, anim banksy mlkshk. Velit VHS truffaut keytar 3 wolf moon yr. Biodiesel typewriter cliche skateboard tonx, terry richardson dolor truffaut eu. You probably haven't heard of them commodo officia, aliquip organic in four loko. Magna sint terry richardson, semiotics chillwave chambray banksy ea laboris tempor letterpress trust fund plaid readymade. Flexitarian sartorial occaecat jean shorts pinterest. Shoreditch pop-up vinyl art party butcher mlkshk ut ullamco, cillum in.
                        3 wolf moon et deserunt, marfa put a bird on it sriracha nostrud VHS tempor ennui small batch jean shorts high life. Culpa mixtape try-hard, fashion axe freegan pop-up sunt food truck enim semiotics locavore. Art party farm-to-table shoreditch aute banh mi. Whatever nisi in yr. In messenger bag truffaut art party, gastropub officia incididunt marfa wolf laboris cliche whatever. Brooklyn ad mlkshk, shoreditch fap dreamcatcher bespoke. Ut est sapiente odd future before they sold out yr +1, do tonx nesciunt cardigan VHS.
                        Fingerstache seitan mixtape exercitation retro, cillum excepteur carles magna quinoa gluten-free street art. Beard fingerstache tattooed fanny pack, qui church-key retro banh mi shoreditch brooklyn actually. Cosby sweater vinyl odd future, laboris master cleanse gastropub deep v tousled culpa shoreditch ad. Laborum beard pitchfork, tofu deep v church-key tempor sartorial aute delectus. Laborum chillwave duis, williamsburg sunt sapiente vero wes anderson. Butcher retro before they sold out, mlkshk sed neutra salvia. Irony tonx vice, occaecat bicycle rights banjo tattooed viral ethnic nesciunt umami ugh eiusmod."""
                },
                  { name: 'Mozilla',
                    twitter: '@mozilla',
                    website: 'mozilla.org',
                    description: """Esse letterpress carles, jean shorts laborum fap banjo. Cliche food truck Austin ugh, semiotics duis 3 wolf moon deep v cillum. Sunt meggings freegan, viral vinyl biodiesel eu yr qui labore disrupt pork belly officia. Labore do 3 wolf moon fugiat, flannel ullamco velit blog enim. VHS art party next level swag. Banjo pop-up tonx, irure ethical iphone pariatur +1. Organic cupidatat locavore cred 90's.
                                  Ut farm-to-table put a bird on it eu. Raw denim dreamcatcher tofu stumptown keffiyeh. Yr blog bespoke, 8-bit cray ethical synth kogi salvia pop-up. Typewriter plaid assumenda, meh nostrud artisan brooklyn pop-up reprehenderit single-origin coffee yr pitchfork carles american apparel 3 wolf moon. Eiusmod mixtape 8-bit, beard enim fashion axe swag proident pop-up scenester banh mi synth voluptate master cleanse stumptown. Nulla banjo art party blue bottle, shoreditch banksy lomo veniam wes anderson minim. Excepteur food truck dreamcatcher, sustainable cupidatat literally cosby sweater ullamco dolor intelligentsia single-origin coffee iphone Austin high life esse.
                                  Blog tattooed ea nulla, authentic readymade 3 wolf moon artisan raw denim direct trade irure put a bird on it 8-bit yr. Semiotics single-origin coffee locavore chambray, direct trade keffiyeh neutra fugiat. Placeat ugh lo-fi, deserunt next level ut tonx sriracha. Polaroid retro deep v, biodiesel PBR organic hoodie. Godard high life you probably haven't heard of them fanny pack. Ethical sunt ennui laborum artisan. Banh mi polaroid squid, ut sint disrupt godard aliquip williamsburg minim."""
                },
                  { name: '37signals',
                    twitter: '@37signals',
                    website: '37signals.com',
                    description: """Enim jean shorts banh mi next level, +1 wolf terry richardson minim put a bird on it helvetica odd future typewriter. Mollit veniam minim ennui actually aesthetic. Meggings small batch non, actually food truck swag helvetica. Readymade raw denim fap disrupt american apparel, actually semiotics ut umami synth artisan 8-bit aliquip chillwave scenester. Seitan typewriter duis velit wolf twee quis, iphone literally cray carles do. Fingerstache wayfarers flexitarian, keffiyeh next level +1 excepteur ad lomo. Scenester biodiesel art party dolore.
                                  Laboris occupy whatever church-key, messenger bag ut cillum four loko flannel hoodie artisan trust fund. Flexitarian brooklyn craft beer placeat laborum mixtape. Forage skateboard fashion axe pug ut, freegan ullamco beard mumblecore next level cray yr. Church-key vero readymade mollit. Lomo bicycle rights veniam actually, next level squid single-origin coffee cosby sweater. Mumblecore bespoke neutra nisi non, aliquip selfies veniam sint post-ironic helvetica pug marfa brooklyn. Sapiente pork belly assumenda, farm-to-table esse etsy viral +1 try-hard pop-up laborum.
                                  Thundercats et synth readymade dolore, small batch nostrud blog salvia wayfarers. Eu etsy forage Austin adipisicing helvetica. Tonx ugh proident, ex fashion axe locavore vegan banh mi. Vegan artisan chambray, pop-up put a bird on it disrupt magna. Irony sartorial pour-over, commodo fashion axe selvage messenger bag put a bird on it 8-bit craft beer helvetica pop-up tattooed cred mollit. Williamsburg high life dolore pinterest, pop-up skateboard sriracha vero cosby sweater. Enim tofu pitchfork, pug nihil letterpress irure typewriter synth.
                                  Vegan sriracha sint tumblr umami mumblecore selvage, laborum brunch seitan before they sold out sartorial laboris cliche. Mcsweeney's squid est tofu, ut iphone odd future dolore messenger bag twee excepteur sint dolor post-ironic nisi. Assumenda 8-bit DIY bushwick, messenger bag ullamco lo-fi fanny pack sapiente organic occupy. Ennui wes anderson semiotics, fixie next level trust fund raw denim truffaut you probably haven't heard of them ut assumenda. Cosby sweater neutra YOLO, carles truffaut aesthetic pinterest tonx enim tempor cardigan duis pour-over exercitation. Literally eu chambray, tousled banh mi pickled cillum in officia. Gentrify hoodie hashtag pickled lo-fi, disrupt elit photo booth.
                                  You probably haven't heard of them mumblecore lomo wolf. Swag aliqua incididunt do ea nostrud. Qui banksy seitan, duis sriracha iphone eiusmod banjo thundercats chambray mcsweeney's laboris portland bicycle rights Austin. Minim commodo direct trade laboris. Ut mcsweeney's dolore, +1 mustache squid deserunt. Fixie deserunt carles brooklyn anim intelligentsia, leggings actually banh mi mlkshk. Cliche deserunt laboris, ea ennui nihil mcsweeney's mumblecore PBR sriracha farm-to-table 90's."""
                }])
